### PR TITLE
...

### PR DESCRIPTION
**Pull request by ranakh23**
new icons edit

### CODE REVIEW

**Comment by ftadel** [comment]
There are conflicts in your PR... Is this work in progress?

**Comment by ranakh23** [comment]
Conflicts with the other PR you mean ?

**Comment by ranakh23** [comment]
Oh sorry forgot to add one thing

**Comment by ftadel** [comment]
I also removed the previous icons, I guess you were not using them any more: 
https://github.com/brainstorm-tools/bst-java/commit/bc5737d85121f3754e4d912745839a6d1765c7bc

Java package recompiled and pushed to Brainstorm:
https://github.com/brainstorm-tools/brainstorm3/commit/6490825fb3a3db5342e07fbe24dc3df3722bf1dc

**Pull request merged**
